### PR TITLE
Add replacestate link type

### PR DESCRIPTION
**Pull request by tbo**
In some use cases it is useful to change the url without reseting the scroll position. It solves #82.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by ross-pfahler** [comment]
I think there should be a test to verify in https://github.com/yahoo/flux-router-component/blob/master/tests/unit/lib/RouterMixin-test.js

**Comment by lingyan** [comment]
@tbo  Thanks for your contribution!

I like it, and am thinking it could actually be applied to both replace state and push state.  Like [in your product size use case](https://github.com/yahoo/flux-router-component/issues/82), your product person can also decide to use pushState instead of replaceState.

What do you think about making `preserveScrollPosition` and `replaceState` as part of `nav.params` with both default to `false`, and stick with the DEFAULT/CLICK nav type?

BTW, `nav.params` can be configured as `navParams` on the `NavLink`.

**Comment by tbo** [comment]
@lingyan Thanks for your suggestions. I added it. But instead of encapsulating preserveScrollPosition in an option object I passed it directly. I hope that is okay.

**Comment by lingyan** [comment]
@tbo Thanks for updating it!  Passing the params as props is totally what I wanted :)

Could you add the params to the [NavLink doc](https://github.com/yahoo/flux-router-component/blob/master/docs/navlink.md#navlink)?

Also, can we do the same for `replaceState`?  So it can be passed in as another prop like `this.props.replaceState`?  That way, we can keep the code DRY by removing the repeated code in https://github.com/tbo/flux-router-component/blob/master/lib/RouterMixin.js#L141-L149 and https://github.com/tbo/flux-router-component/blob/master/lib/RouterMixin.js#L153-L161.  And we won't really need to introduce a new nav type.

```js
        switch (navType) {
            case TYPE_CLICK:
            case TYPE_DEFAULT:
                historyState = {params: (nav.params || {})};
                if(this._enableScroll) {
                    if (!nav.preserveScrollPosition) {
                        resetScrollPosition();
                    } else {
                        historyState.scroll = {x: window.scrollX, y: window.scrollY};
                    }
                }
                pageTitle = nav.params && nav.params.pageTitle || null;
                if (nav.replaceState) {
                    this._history.replaceState(historyState, pageTitle, newState.route.url);
                } else {
                    this._history.pushState(historyState, pageTitle, newState.route.url);
                }
                break;
            case TYPE_POPSTATE:
               ...
```

**Comment by tbo** [comment]
@lingyan I removed the repeated code, but I opted to keep the additional nav type. What do you think about it? I also added your suggestions regarding NavLink.

**Comment by lingyan** [comment]
@tbo  Thanks a lot for the update.  My two cents:  I actually think it would be better (and easier to read) to just make some minor change to the previous commit, like this:

```js
        switch (navType) {
            case TYPE_CLICK:
            case TYPE_DEFAULT:
            case TYPE_REPLACESTATE:        
                historyState = {params: (nav.params || {})};
                if(this._enableScroll) {
                    if (!nav.preserveScrollPosition) {
                        resetScrollPosition();
                    } else {
                        historyState.scroll = {x: window.scrollX, y: window.scrollY};
                    }
                }
                pageTitle = nav.params && nav.params.pageTitle || null;
                if ((navType === TYPE_REPLACESTATE) || nav.replaceState) {
                    this._history.replaceState(historyState, pageTitle, newState.route.url);
                } else {
                    this._history.pushState(historyState, pageTitle, newState.route.url);
                }
                break;
            case TYPE_POPSTATE:
                if (this._enableScroll) {

```
WDYT?

**Comment by tbo** [comment]
@lingyan Done.

**Comment by lingyan** [comment]
Cool.  Thanks @tbo!  There is a minor tweak to move the resetScrollPosition function out for performance best practice.  I will fix it after merging.

**Pull request merged**
