### PR TITLE
allow react 0.13 rc releases. can't use <=0.13.x or <0.14.0 because of npm 2.0

### PR DESCRIPTION
**Pull request by lingyan**
@redonkulus addresses #77

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by redonkulus** [comment]
:shipit:

**Comment by redonkulus** [comment]
One build failed though.

**Comment by lingyan** [comment]
fluke with npm install on io.js.  restarted the build

**Comment by lingyan** [comment]
For some reason, github is not getting updated even though the restarted travis build succeeded: https://travis-ci.org/yahoo/flux-router-component/builds/52335441

Merging

**Pull request merged**
